name:                hysteria-shooter
version:             0.1.0.0
github:              "4Denthusiast/hysteria-shooter"
license:             CC-BY-4.0
author:              "4D enthusiast"
maintainer:          "example@example.com"
copyright:           "2021 4D enthusiast"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/4Denthusiast/hysteria-shooter#readme>

dependencies:
- base >= 4.7 && < 5
- bytes
- bytestring
- clock
- containers
- directory
- extra
- filepath
- gtk >= 0.15.5
- mtl
- network-simple
- text
- transformers

library:
  source-dirs: src

executables:
  hysteria-shooter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hysteria-shooter
  hysteria-server:
    main:                Main.hs
    source-dirs:         server
    dependencies:
    - hysteria-shooter

tests:
  hysteria-shooter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hysteria-shooter
